### PR TITLE
bug: do not reach to quorum on replication call

### LINKED ISSUE #46: LogServer Collect should not reach to Raft/Storage
When Metrics are being collected from LogServer, the Raft quorum is consulted. This should be avoided, Gauges should be populated asynchronously instead.

### PR DESCRIPTION
**Pull request by coufalja**
Removed the applied index metrics from Replication API, update index in table FSM instead.

Fixes #46

### CODE REVIEW

File: storage/table/fsm/fsm.go [hunk 1]
```diff
@@ -156,7 +156,12 @@ func (p *FSM) Open(_ <-chan struct{}) (uint64, error) {
 		p.log.Errorf("unable to register metrics for FSM: %s", err)
 	}
 
-	return readLocalIndex(db, sysLocalIndex)
+	idx, err := readLocalIndex(db, sysLocalIndex)
+	if err != nil {
+		return 0, err
+	}
+	p.metrics.applied.Store(idx)
+	return idx, err
```
Comment (tsvoboda-wandera) [inline storage/table/fsm/fsm.go:164]: minor: since the err is already handled, explicitly returning `nil might be more readable
```suggestion
	return idx, nil
```

**Review by tsvoboda-wandera — DISMISSED** [review]

**Review by tsvoboda-wandera — APPROVED** [review]
